blog/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.Blogs.as_view(), name='posts'),
    path('search/', views.SearchResultsListView.as_view(), name='search_results'), 
    path('<slug:slug>/', views.blog_detail, name='blog_detail'),
    path('comments/<int:pk>/', views.comment_thread, name='comment_thread'),
    path('comments/<int:pk>/delete/', views.comment_delete, name='comment_delete'),
    path('<category>', views.blog_category, name="blog_category"),
]

newsletters/urls.py
from django.urls import path
from .views import newsletter_subscribe, newsletter_unsubscribe, newsletter_control

app_name = 'newsletters'
urlpatterns = [
path('subscribe', newsletter_subscribe, name='subscribe'),
path('unsubscribe', newsletter_unsubscribe, name='unsubscribe'),
path('newsletter_control', newsletter_control, name='newsletter')
]

personal_website/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from .views import Home


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Home.as_view(), name='home' ),
    path('accounts/', include('accounts.urls')),
    path('blog/', include('blog.urls')),
    path('projects/', include('projects.urls')),
    path('contact/', include('contact.urls')),
    path('about/', include('about.urls')),
    path('newsletters/', include('newsletters.urls', namespace='newsletters')),
    path('newsletter_control/', include('newsletter_control_panel.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG: # new
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
] + urlpatterns

newsletters/models.py
from django.db import models

class NewsUsers(models.Model):
    email = models.EmailField()
    date_added = models.DateField(auto_now_add=True)
    
    class Meta:
        verbose_name = "NewsUser"
        verbose_name_plural = "NewsUsers"

    def __str__(self):
        return self.email
        
    objects = models.Manager()


class Newsletter(models.Model):
    EMAIL_STATUS_CHOICES = (
        ('Draft', 'Draft'),
        ('Published', 'Published')
    )
    subject = models.CharField(max_length=250)
    body    = models.TextField()
    email   = models.ManyToManyField(NewsUsers)
    status  = models.CharField(max_length=10, choices=EMAIL_STATUS_CHOICES)
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    
    objects = models.Manager()

    def __str__(self):
        return self.subject

newsletters/forms.py
from django import forms
from pagedown.widgets import PagedownWidget
from .models import NewsUsers, Newsletter

class NewsUserForm(forms.ModelForm):
    class Meta:
        model = NewsUsers
        fields = ['email']

    def clean_email(self):
        email = self.cleaned_data.get('email')
        return email

class NewsletterCreationForm(forms.ModelForm):
    body = forms.CharField(widget=PagedownWidget())
    class Meta:
        model = Newsletter
        fields = ['subject', 'body', 'email', 'status']
    

newsletters/views.py
from django.conf import settings
from django.core.mail import send_mail, EmailMultiAlternatives
from django.template.loader import get_template
from django.contrib import messages
from django.shortcuts import render
from .forms import NewsUserForm, NewsletterCreationForm
from . models import NewsUsers, Newsletter


def newsletter_subscribe(request):
    form = NewsUserForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        if NewsUsers.objects.filter(email=instance.email).exists():
            messages.warning(request,
                        "your Email Already exists in our database",
                        "alert alert-warning alert-dismissible")
        else:
            instance.save()
            messages.success(request,
                            "Your email has been submitted to the database",
                            "alert alert-success alert-dismissible")

            subject = "Thank You For Joining Our Newsletter"
            from_email = settings.EMAIL_HOST_USER
            to_email = [instance.email]

            with open(settings.BASE_DIR + "/newsletters/templates/subscribe_email.txt") as f:
                newsletter_message = f.read()
            
            message = EmailMultiAlternatives(subject=subject, body=newsletter_message, from_email=from_email, to=to_email)
            html_template = get_template("subscribe_email.html").render()
            message.attach_alternative(html_template, "text/html")
            message.send()

    context = {
        'form': form
    }
    template = "subscribe.html"
    return render(request, template, context)

def newsletter_unsubscribe(request):
    form = NewsUserForm(request.POST or None)

    if form.is_valid():
        instance = form.save(commit=False)
        if NewsUsers.objects.filter(email=instance.email).exists():
            NewsUsers.objects.filter(email=instance.email).delete()
            messages.success(request,
                            "Your email has been removed",
                            "alert alert-success alert-dismissible")

            subject = "You have been unsubscribed"
            from_email = settings.EMAIL_HOST_USER
            to_email = [instance.email]
            with open(settings.BASE_DIR + "/newsletters/templates/unsubscribe_email.txt") as f:
                newsletter_message = f.read()
            
            message = EmailMultiAlternatives(subject=subject, body=newsletter_message, from_email=from_email, to=to_email)
            html_template = get_template("unsubscribe_email.html").render()
            message.attach_alternative(html_template, "text/html")
            message.send()

        else:
            messages.warning(request,
                        "Sorry we didn't find your email address",
                        "alert alert-warning alert-dismissible")
    
    context ={
        'form': form
    }
    template = 'unsubscribe.html'
    return render(request, template, context)

def newsletter_control(request):
    form = NewsletterCreationForm(request.POST or None)

    if form.is_valid():
        instance = form.save()
        newsletter = Newsletter.objects.get(id=instance.id)
        if newsletter.status == "Published":
            subject = newsletter.subject
            body    = newsletter.body
            from_email = settings.EMAIL_HOST_USER
            for email in newsletter.email.all():
                send_mail(subject=subject, from_email=from_email, recipient_list=[email], message=body, fail_silently=True)
        
    context = {
        'form': form,
    }
    template = 'newsletter_control.html'
    return render(request, template, context)

newsletters/templates/newsletter_control.html
{% extends 'control_base.html' %}

{% block content %}
<div class="container-fluid">
  <div class="row">
    <div class="col-md-12">
        {% block form %}
          {% include 'newsletter_form.html' %}
        {% endblock %}
    </div>
  </div>
</div>
{% endblock %}

newsletters/templates/newsletter_form.html
{% extends 'control_base.html' %}

{% load crispy_forms_tags %}

{% block extra_head %}
  {{ form.media }}
{% endblock %}

{% block title %}Newsletter{% endblock %}

{% block form %}
<div class="container-fluid">

    <form action="{% url 'newsletters:newsletter' %}" method="post" novalidate>
      {% csrf_token %}
    
      {{ form.subject|as_crispy_field }}
      {{ form.body|as_crispy_field }}
    
      <div class="row">
        <div class="col-6">
          {{ form.email|as_crispy_field }}
        </div>
        <div class="col-6">
          {{ form.status|as_crispy_field }}
        </div>
      </div>
      
      <button type="submit" class="btn btn-success">Save Newsletter</button>
    </form>
    
    </div>
{% endblock %}

newsletters/templates/subscribe.html
{% extends "base.html" %}

{% block page_content %}

<div class="container">
    <div class="row ">
        <div class="col-12">
            <div class="container">
                <h2>Stay Updated</h2>
                <p>Subscribe to our newsletter to get our latest news.</p>
                {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %} role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                {% endfor %}
                {% else %}
                <form action="{% url 'newsletters:subscribe' %}" method="POST">{% csrf_token %}
                  <input type="email" name="email" placeholder="Enter email address">
                  <input type="submit" value="Subscribe">
                </form>
                {% endif %}
              </div>
        </div>
    </div>
</div>

{% endblock page_content %}

newsletters/templates/subscribe_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Welcom to letsflyonthewebsky Newsletter</h2>
    <p>Thank you for joining</p>
    <p>To unsubscribe visit this link: <a href="http://127.0.0.1:8000/newsletters/unsubscribe">Unsubscribe</a></p>
</body>
</html>

newsletters/templates/unsubscribe.html
{% extends "base.html" %}

{% block page_content %}

<div class="container-fluid">
    <div class="row">
        <div class="col-12">
            <div class="ft-main">
                <div class="ft-main-item">
                <h2 class="ft-title">Do you unsubscribe?</h2>
                <p>Unsubscribe to newsletter.</p>
                {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="{{ message.tags }}" {% endif %} role="alert">
                  {{ message }}
                  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                    <span aria-hidden="true">&times;</span>
                  </button>
                </div>
                {% endfor %}
                {% else %}
                <form action="{% url 'newsletters:unsubscribe' %}" method="POST">{% csrf_token %}
                  <input type="email" name="email" placeholder="Enter email address">
                  <input type="submit" value="Unsubscribe">
                </form>
                {% endif %}
              </div>
            </div>
        </div>
    </div>
</div>

{% endblock page_content %}

newsletters/templates/unsubscribe_email.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h2>Sorry to see you go</h2>
    <p>Bye Bye</p>
</body>
</html>